### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by supertobi** [cskollar/idasen2mqtt#1]
Hi,

I have an IKEA IDÃSEN standing desk and would like to control it from my desktop PC. all I need is a small standalone (python) program to move the desk to a defined position. Now I'd like to look into your code but the code is missing a license. MIT or GPL would be fine.
And perhaps you can improve your readme with some hints how you discovered the needed commands.

**Comment by cskollar** [comment]
Hi,

Thanks for your interest! I've added a GPL license and updated the readme.
